require("config.lazy")
require("config.autocmd")
require("config.highlight")
require("config.icons")
require("config.options")
require("config.remap")
require("config.statusline")
require("config.winbar")
